# Generated by Django 4.2.6 on 2023-10-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='img/movie_posters/', verbose_name='Póster'),
        ),
    ]
