# Generated by Django 4.2.6 on 2023-10-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='static/img/movie_posters/', verbose_name='Póster'),
        ),
    ]
