# Generated by Django 4.2.6 on 2023-10-21 04:02

import app.movie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to=app.movie.models.upload_movie_poster, verbose_name='Póster'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='url_movie',
            field=models.URLField(verbose_name='URL de la película'),
        ),
    ]
